import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbard from "@/components/layout/Navbard";
import Providers from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-slate-200`}
    >
      <Providers>

   
      <body className="min-h-full h-full flex flex-col w-full ">
        <header>
          <Navbard />
        </header>
        <div className="flex w-full h-full ">
          <Sidebar />
          {children}
        </div>
        <footer></footer>
      </body>
      </Providers>
    </html>
  );
}
